[package]
name = "sum2020"
version = "0.1.0"
authors = ["Jonas Otto (ottojo) <jottosmail@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
